INSERT INTO tb_gamelist (name) VALUES ('Ação');
INSERT INTO tb_gamelist (name) VALUES ('Aventura');
INSERT INTO tb_gamelist (name) VALUES ('Estratégia');
INSERT INTO tb_gamelist (name) VALUES ('Esporte');
INSERT INTO tb_gamelist (name) VALUES ('Corrida');
INSERT INTO tb_gamelist (name) VALUES ('Horror');

INSERT INTO tb_game (title, game_year, genre, platforms, score, img_url, short_description, long_description) VALUES ('Diablo IV', 2023, 'RPG', 'PC', 3.8, 'https://blz-contentstack-images.akamaized.net/v3/assets/blt77f4425de611b362/blt6d7b0fd8453e72b9/646e720a71d9db111a265e8c/d4-open-graph_001.jpg', 'Diablo IV é um RPG de ação desenvolvido pela empresa Blizzard Entertainment, sendo o quarto título da série Diablo', 'Situado no mundo de Santuário, Diablo IV se passa logo após Diablo III: Reaper of Souls. Cultistas invocaram a principal antagonista e filha de Mephisto, Lilith. Depois dos eventos dos jogos anteriores.');
INSERT INTO tb_game (title, game_year, genre, platforms, score, img_url, short_description, long_description) VALUES ('Dead Space Remake', 2023, 'RPG', 'PC, PS5, Xbox', 4.6, 'https://cdn1.epicgames.com/offer/4ec958d5e4b6429aadbc116cee0b6ea0/EGS_DeadSpace_MotiveStudio_S1_2560x1440-48626121e40a971f59b60451fa3d8636', 'Dead Space Remake é um jogo eletrônico de survival horror e ficção científica desenvolvido pela Motive Studios e publicado pela Electronic Arts.', 'O jogo mantém o mesmo enredo básico do original. Situado no século 26, a história segue o engenheiro Isaac Clarke, um tripulante em uma embarcação de reparos designada para o USG Ishimura, uma enorme nave de mineração planetária.');
INSERT INTO tb_game (title, game_year, genre, platforms, score, img_url, short_description, long_description) VALUES ('Resident Evil 4 Remake', 2023, 'RPG', 'PC, PS4, PS5, Xbox', 4.8, 'https://jornalogoncalense.com.br/wp-content/uploads/2022/06/idmjlql391g51.png', 'Resident Evil 4, conhecido no Japão como Biohazard RE:4, é um jogo eletrônico de survival horror desenvolvido e publicado pela Capcom.', 'Assim como no jogo original, o jogador organiza seu inventário com uma "caixa de anexos". Novidade no remake, um sistema de criação permite ao jogador criar itens e munições usando recursos coletados ao longo do jogo.');
INSERT INTO tb_game (title, game_year, genre, platforms, score, img_url, short_description, long_description) VALUES ('Star Wars Jedi: Survivor', 2023, 'MMO RPG', 'PC, PS5, Xbox', 3.5, 'https://gamerspoilerbrasil.b-cdn.net/wp-content/uploads/2023/06/Jedi-Switch-1.jpeg', 'Star Wars Jedi: Survivor é um jogo de ação e aventura desenvolvido pela Respawn Entertainment e publicado pela Electronic Arts.', 'O rastreamento de raio em tempo real, entre outros recursos de última geração, de acordo com Stig Asmussen, permite que o Respawn funcione "com uma qualidade muito acima de qualquer coisa que já desenvolvemos antes".');
INSERT INTO tb_game (title, game_year, genre, platforms, score, img_url, short_description, long_description) VALUES ('The Legend of Zelda: Tears of the Kingdom', 2023, 'RPG', 'Nitendo', 4.2, 'https://wp-uploads.qualbert.com/2023/06/Tears-of-the-Kingdom-wallpaper-1170x720.jpg', 'The Legend of Zelda: Tears of the Kingdom é um jogo eletrônico de ação-aventura desenvolvido e publicado pela Nintendo.', 'Tears of the Kingdom recebeu aclamação universal no agregador de notas Metacritic. A crítica especializada elogiou o mundo aberto expandido introduzido em Breath of the Wild.');
INSERT INTO tb_game (title, game_year, genre, platforms, score, img_url, short_description, long_description) VALUES ('The Witcher 3: Wild Hunt', 2015, 'RPG', 'PC, PS4, PS5, Xbox', 4.2, 'https://cdn1.epicgames.com/offer/14ee004dadc142faaaece5a6270fb628/EGS_TheWitcher3WildHuntCompleteEdition_CDPROJEKTRED_S1_2560x1440-82eb5cf8f725e329d3194920c0c0b64f', 'The Witcher 3: Wild Hunt é um jogo eletrônico de RPG de ação em mundo aberto desenvolvido pela CD Projekt RED.', 'The Witcher 3: Wild Hunt foi amplamente aclamado pela crítica, com alguns considerando-no como um dos melhores jogos de todos os tempos.');
INSERT INTO tb_game (title, game_year, genre, platforms, score, img_url, short_description, long_description) VALUES ('Cuphead', 2017, 'RPG', 'PC', 4.7, 'https://assets.nintendo.com/image/upload/c_fill,w_1200/q_auto:best/f_auto/dpr_2.0/ncom/software/switch/70010000016330/d94d2186ef03c930392253c83c84af0c73b7e57cd902a526b09b4155a25930fe', 'Cuphead é um jogo eletrônico de run and gun e plataforma criado pelos irmãos canadenses Chad e Jared Moldenhauer através da Studio MDHR.', 'Cuphead apresenta dois jogadores que controlam o personagem-título e seu irmão Mugman, em uma aventura através da fictícia Inkwell Isle para derrotar uma série de chefes para pagar uma dívida adquirida com o diabo.');
INSERT INTO tb_game (title, game_year, genre, platforms, score, img_url, short_description, long_description) VALUES ('Age of Empires IV', 2021, 'RPG', 'PC, Xbox', 3.2, 'https://assets.xboxservices.com/assets/f6/c1/f6c1b625-e46f-429b-9727-9a24c3111737.jpg?n=7211566_GLP-Page-Hero-0_1083x609.jpg', 'Age of Empires IV é um jogo eletrônico de estratégia em tempo real desenvolvido pela Relic Entertainment e Worlds Edge Studio para o Windows 10.', 'Os eventos do jogo são ambientados na Idade Média. Entre outras, haverá uma campanha contando uma história sobre a conquista normanda da Inglaterra.');
INSERT INTO tb_game (title, game_year, genre, platforms, score, img_url, short_description, long_description) VALUES ('FIFA', 2023, 'Jogo de Plataforma', 'PC, PS5, Xbox', 2.4, 'https://classic.exame.com/wp-content/uploads/2021/10/fifa-22-review-capa_7kn3.jpg?quality=70&strip=info&w=1024', 'EA Sports FC, também conhecido como EAFC (anteriormente conhecido como FIFA, FIFA Football ou FIFA Soccer), é uma série de videojogos de futebol, lançados anualmente pela Electronic Arts (EA) sobre a chancela EA Sports.', 'Quando a série começou em 1993, tornou-se notável por ser o primeiro jogo que tinha uma licença oficial da FIFA, o organismo que coordena o futebol mundial. Os mais recentes títulos da série contém várias ligas nacionais licenciadas de todo o mundo.');
INSERT INTO tb_game (title, game_year, genre, platforms, score, img_url, short_description, long_description) VALUES ('Forza Horizon 5', 2021, 'Jogo de Plataforma', 'PC, Xbox', 4.4, 'https://s2-techtudo.glbimg.com/r5FN3juyaUyWQn6O5U0WlcQRACQ=/0x0:2400x1350/984x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_08fbf48bc0524877943fe86e43087e7a/internal_photos/bs/2021/o/F/TT2xyvRXuQCXuIJ3nC4Q/forzahorizon5-keyart-horiz-rgb-final.jpg', 'Forza Horizon 5 é um jogo eletrônico de corrida desenvolvido pela Playground Games e publicado pela Xbox Game Studios.', 'O jogo tem o maior mapa de toda a série Forza Horizon, sendo 50% maior do que o de Forza Horizon 4, além de também ter o ponto mais alto da série Horizon.');

INSERT INTO tb_belonging (gamelist_id, game_id, position) VALUES (1, 2, 0);
INSERT INTO tb_belonging (gamelist_id, game_id, position) VALUES (1, 6, 1);
INSERT INTO tb_belonging (gamelist_id, game_id, position) VALUES (2, 4, 0);
INSERT INTO tb_belonging (gamelist_id, game_id, position) VALUES (2, 5, 1);
INSERT INTO tb_belonging (gamelist_id, game_id, position) VALUES (3, 8, 0);
INSERT INTO tb_belonging (gamelist_id, game_id, position) VALUES (4, 9, 0);
INSERT INTO tb_belonging (gamelist_id, game_id, position) VALUES (5, 10, 0);
INSERT INTO tb_belonging (gamelist_id, game_id, position) VALUES (6, 1, 0);
INSERT INTO tb_belonging (gamelist_id, game_id, position) VALUES (6, 3, 1);
INSERT INTO tb_belonging (gamelist_id, game_id, position) VALUES (6, 7, 2);